const express = require('express');
const fs = require('fs').promises;
const path = require('path');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 3000;
const DATA_FILE = path.join(__dirname, 'data.json');

// Middleware
app.use(cors());
app.use(express.json());
app.use(express.static('public')); // Serve static files from 'public' directory

// Utility function to read todos from file
async function readTodos() {
    try {
            const data = await fs.readFile(DATA_FILE, 'utf8');
                    return JSON.parse(data);
                        } catch (error) {
                                // If file doesn't exist, return empty array
                                        if (error.code === 'ENOENT') {
                                                    return [];
                                                            }
                                                                    throw error;
                                                                        }
                                                                        }

                                                                        // Utility function to write todos to file
                                                                        async function writeTodos(todos) {
                                                                            await fs.writeFile(DATA_FILE, JSON.stringify(todos, null, 2));
                                                                            }

                                                                            // Routes

                                                                            // GET /api/todos - Get all todos
                                                                            app.get('/api/todos', async (req, res) => {
                                                                                try {
                                                                                        const todos = await readTodos();
                                                                                                res.json(todos);
                                                                                                    } catch (error) {
                                                                                                            console.error('Error reading todos:', error);
                                                                                                                    res.status(500).json({ error: 'Failed to read todos' });
                                                                                                                        }
                                                                                                                        });

                                                                                                                        // POST /api/todos - Create a new todo
                                                                                                                        app.post('/api/todos', async (req, res) => {
                                                                                                                            try {
                                                                                                                                    const { text } = req.body;
                                                                                                                                            
                                                                                                                                                    if (!text || text.trim() === '') {
                                                                                                                                                                return res.status(400).json({ error: 'Todo text is required' });
                                                                                                                                                                        }

                                                                                                                                                                                const todos = await readTodos();
                                                                                                                                                                                        const newTodo = {
                                                                                                                                                                                                    id: Date.now(),
                                                                                                                                                                                                                text: text.trim(),
                                                                                                                                                                                                                            completed: false,
                                                                                                                                                                                                                                        createdAt: new Date().toISOString()
                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                        todos.push(newTodo);
                                                                                                                                                                                                                                                                await writeTodos(todos);

                                                                                                                                                                                                                                                                        res.status(201).json(newTodo);
                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                    console.error('Error creating todo:', error);
                                                                                                                                                                                                                                                                                            res.status(500).json({ error: 'Failed to create todo' });
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                // PUT /api/todos/:id - Update a specific todo
                                                                                                                                                                                                                                                                                                app.put('/api/todos/:id', async (req, res) => {
                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                            const todoId = parseInt(req.params.id);
                                                                                                                                                                                                                                                                                                                    const { text, completed } = req.body;

                                                                                                                                                                                                                                                                                                                            const todos = await readTodos();
                                                                                                                                                                                                                                                                                                                                    const todoIndex = todos.findIndex(todo => todo.id === todoId);

                                                                                                                                                                                                                                                                                                                                            if (todoIndex === -1) {
                                                                                                                                                                                                                                                                                                                                                        return res.status(404).json({ error: 'Todo not found' });
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                        // Update todo properties
                                                                                                                                                                                                                                                                                                                                                                                if (text !== undefined) {
                                                                                                                                                                                                                                                                                                                                                                                            todos[todoIndex].text = text.trim();
                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                            if (completed !== undefined) {
                                                                                                                                                                                                                                                                                                                                                                                                                        todos[todoIndex].completed = Boolean(completed);
                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                        await writeTodos(todos);
                                                                                                                                                                                                                                                                                                                                                                                                                                                res.json(todos[todoIndex]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Error updating todo:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({ error: 'Failed to update todo' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // DELETE /api/todos/:id - Delete a specific todo
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.delete('/api/todos/:id', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const todoId = parseInt(req.params.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const todos = await readTodos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const todoIndex = todos.findIndex(todo => todo.id === todoId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (todoIndex === -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return res.status(404).json({ error: 'Todo not found' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const deletedTodo = todos.splice(todoIndex, 1)[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await writeTodos(todos);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.json({ message: 'Todo deleted successfully', todo: deletedTodo });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('Error deleting todo:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.status(500).json({ error: 'Failed to delete todo' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // PUT /api/todos - Replace all todos (bulk update)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.put('/api/todos', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const todos = req.body;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!Array.isArray(todos)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return res.status(400).json({ error: 'Todos must be an array' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Validate each todo object
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const validatedTodos = todos.map(todo => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    id: todo.id || Date.now() + Math.random(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                text: todo.text || '',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            completed: Boolean(todo.completed),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        createdAt: todo.createdAt || new Date().toISOString()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }));

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await writeTodos(validatedTodos);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.json({ message: 'All todos updated successfully', count: validatedTodos.length });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('Error updating all todos:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    res.status(500).json({ error: 'Failed to update todos' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // DELETE /api/todos - Delete all todos
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.delete('/api/todos', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await writeTodos([]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.json({ message: 'All todos deleted successfully' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.error('Error deleting all todos:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                res.status(500).json({ error: 'Failed to delete all todos' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Serve the data.json file directly (for compatibility with frontend)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    app.get('/data.json', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const todos = await readTodos();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.json(todos);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error('Error reading data.json:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            res.status(500).json({ error: 'Failed to read data' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Error handling middleware
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.use((err, req, res, next) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.error(err.stack);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        res.status(500).json({ error: 'Something went wrong!' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Start server
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log(`✅ Server is running on http://localhost:${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                console.log(`📁 Serving static files from 'public' directory`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`💾 Data file: ${DATA_FILE}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });